### ISSUE TITLE
hompage value is hardcoded in apiwrapper

### ISSUE THREAD

**Issue by creighton** [adlnet/SCORM-to-TLA-Roadmap#2]
see https://github.com/adlnet/SCORM-to-TLA-Roadmap/blob/master/examples/RosesCourseConversion/RosesSCORM2004Converted/Shared/JavaScript/APIWrapper.js#L162

**Comment by jono-poltrack** [comment]
All initialization requirements have been moved to the LMS (via cmi.launch_data).  This update is complete in SCORM 2004 resources, but not in SCORM Version 1.2.  Another issue is open for this request.
